import { existsSync, readFileSync, writeFileSync, unlinkSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const ROOT = path.resolve(__dirname, '../..');
export const ENV_LOCAL_PATH = path.join(ROOT, '.env.local');
export const ENV_EXAMPLE_PATH = path.join(ROOT, '.env.example');
export const DEV_ENV_PATH = path.join(ROOT, '.env.development.local');
export const DEV_PROFILE_KEY = 'FRAGMENTSTUDY_DEV_PROFILE';

export const DEV_PROFILES = {
  REMOTE: 'remote',
  LOCAL_SUPABASE: 'local-supabase',
  GUEST: 'guest',
};

const MANAGED_SUPABASE_KEYS = new Set([
  'VITE_SUPABASE_URL',
  'VITE_SUPABASE_ANON_KEY',
  'VITE_AUTH_EMAIL_DELIVERY_ENABLED',
]);

const KNOWN_ENV_KEYS = [
  'VITE_SUPABASE_URL',
  'VITE_SUPABASE_ANON_KEY',
  'VITE_SUPABASE_BROWSER_URL',
  'VITE_PLATFORM_AI_ENABLED',
  'VITE_AUTH_EMAIL_DELIVERY_ENABLED',
  'QINIU_API_KEY',
  'QINIU_API_ENDPOINT',
  'QINIU_MODEL',
  'VITE_FAL_KEY',
];

export function parseEnvFile(filePath) {
  if (!existsSync(filePath)) return new Map();
  const entries = new Map();
  for (const line of readFileSync(filePath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    entries.set(trimmed.slice(0, eq).trim(), trimmed.slice(eq + 1).trim());
  }
  return entries;
}

export function formatEnvFile(entries, headerLines = []) {
  const lines = [...headerLines];
  if (lines.length > 0 && lines[lines.length - 1] !== '') lines.push('');
  for (const [key, value] of entries) {
    lines.push(`${key}=${value}`);
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

export function maskSecret(value, visible = 4) {
  if (!value) return '（未设置）';
  if (value.length <= visible * 2) return '****';
  return `${value.slice(0, visible)}...${value.slice(-visible)}`;
}

export function getEnvSummary() {
  const local = parseEnvFile(ENV_LOCAL_PATH);
  const dev = parseEnvFile(DEV_ENV_PATH);
  const profile = dev.get(DEV_PROFILE_KEY) ?? local.get(DEV_PROFILE_KEY) ?? '（未选择）';

  return {
    profile,
    hasEnvLocal: existsSync(ENV_LOCAL_PATH),
    hasDevEnv: existsSync(DEV_ENV_PATH),
    supabaseUrl: dev.get('VITE_SUPABASE_URL') ?? local.get('VITE_SUPABASE_URL') ?? '',
    supabaseAnonKey: dev.get('VITE_SUPABASE_ANON_KEY') ?? local.get('VITE_SUPABASE_ANON_KEY') ?? '',
    qiniuApiKey: local.get('QINIU_API_KEY') ?? '',
    qiniuEndpoint: local.get('QINIU_API_ENDPOINT') ?? 'https://api.qnaigc.com/v1',
    qiniuModel: local.get('QINIU_MODEL') ?? 'qwen/qwen3.7-plus',
    platformAi: dev.get('VITE_PLATFORM_AI_ENABLED') ?? local.get('VITE_PLATFORM_AI_ENABLED') ?? '',
    falKey: local.get('VITE_FAL_KEY') ?? '',
  };
}

export function ensureEnvLocalFromExample() {
  if (existsSync(ENV_LOCAL_PATH)) return false;
  if (!existsSync(ENV_EXAMPLE_PATH)) {
    writeFileSync(ENV_LOCAL_PATH, '# FragmentStudy local environment\n', 'utf8');
    return true;
  }
  writeFileSync(ENV_LOCAL_PATH, readFileSync(ENV_EXAMPLE_PATH, 'utf8'), 'utf8');
  return true;
}

export function upsertEnvLocal(updates) {
  if (!existsSync(ENV_LOCAL_PATH)) {
    ensureEnvLocalFromExample();
  }
  const entries = parseEnvFile(ENV_LOCAL_PATH);
  for (const [key, value] of Object.entries(updates)) {
    if (value === undefined || value === null) entries.delete(key);
    else entries.set(key, value);
  }
  writeFileSync(
    ENV_LOCAL_PATH,
    formatEnvFile(entries, ['# FragmentStudy — 本地/远程开发配置（勿提交 Git）']),
    'utf8'
  );
}

export function applyDevProfile(profile, supabaseCredentials = null) {
  const preserved = new Map();
  if (existsSync(DEV_ENV_PATH)) {
    for (const [key, value] of parseEnvFile(DEV_ENV_PATH)) {
      if (!MANAGED_SUPABASE_KEYS.has(key) && key !== DEV_PROFILE_KEY) {
        preserved.set(key, value);
      }
    }
  }

  const entries = new Map(preserved);
  entries.set(DEV_PROFILE_KEY, profile);

  if (profile === DEV_PROFILES.LOCAL_SUPABASE && supabaseCredentials) {
    entries.set('VITE_SUPABASE_URL', supabaseCredentials.apiUrl);
    entries.set('VITE_SUPABASE_ANON_KEY', supabaseCredentials.anonKey);
    entries.set('VITE_AUTH_EMAIL_DELIVERY_ENABLED', 'false');
  }

  if (profile === DEV_PROFILES.GUEST) {
    entries.set('VITE_SUPABASE_URL', '');
    entries.set('VITE_SUPABASE_ANON_KEY', '');
  }

  if (profile === DEV_PROFILES.REMOTE) {
    unlinkDevEnv();
    return;
  }

  const header = [
    '# Generated by npm run dev:menu',
    `# Profile: ${profile}`,
    '# 此文件会覆盖 .env.local 中的同名变量（开发模式）',
  ];

  writeFileSync(DEV_ENV_PATH, formatEnvFile(entries, header), 'utf8');
}

export function unlinkDevEnv() {
  if (existsSync(DEV_ENV_PATH)) unlinkSync(DEV_ENV_PATH);
}

export function listConfigurableKeys() {
  return KNOWN_ENV_KEYS;
}
