import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { networkInterfaces } from 'node:os';
import { fileURLToPath } from 'node:url';
import { DEV_PROFILES, ENV_LOCAL_PATH, DEV_ENV_PATH, getEnvSummary, parseEnvFile } from './env-files.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const ROOT = path.resolve(__dirname, '../..');
export const MOBILE_DIR = path.join(ROOT, 'apps', 'mobile');
export const MOBILE_ENV_PATH = path.join(MOBILE_DIR, '.env');
export const MOBILE_ENV_EXAMPLE_PATH = path.join(MOBILE_DIR, '.env.example');

const MANAGED_MOBILE_KEYS = new Set([
  'EXPO_PUBLIC_SUPABASE_URL',
  'EXPO_PUBLIC_SUPABASE_ANON_KEY',
  'EXPO_PUBLIC_PLATFORM_AI_ENABLED',
  'EXPO_PUBLIC_AUTH_EMAIL_DELIVERY_ENABLED',
]);

export const MOBILE_PLATFORMS = {
  IOS: 'ios',
  ANDROID: 'android',
  DEVICE: 'device',
};

function formatEnvFile(entries, headerLines = []) {
  const lines = [...headerLines];
  if (lines.length > 0 && lines[lines.length - 1] !== '') lines.push('');
  for (const [key, value] of entries) {
    lines.push(`${key}=${value}`);
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

function getLanIp() {
  for (const iface of Object.values(networkInterfaces())) {
    if (!iface) continue;
    for (const addr of iface) {
      if (addr.family === 'IPv4' && !addr.internal) {
        return addr.address;
      }
    }
  }
  return null;
}

/** Map host Supabase URL to what the mobile runtime can reach. */
export function resolveMobileSupabaseUrl(apiUrl, platform) {
  if (!apiUrl) return '';

  let url;
  try {
    url = new URL(apiUrl);
  } catch {
    return apiUrl;
  }

  if (platform === MOBILE_PLATFORMS.ANDROID) {
    if (url.hostname === '127.0.0.1' || url.hostname === 'localhost') {
      url.hostname = '10.0.2.2';
    }
    return url.toString().replace(/\/$/, '');
  }

  if (platform === MOBILE_PLATFORMS.DEVICE) {
    if (url.hostname === '127.0.0.1' || url.hostname === 'localhost') {
      const lanIp = getLanIp();
      if (lanIp) url.hostname = lanIp;
    }
    return url.toString().replace(/\/$/, '');
  }

  // iOS Simulator shares the host network — localhost works as-is.
  return url.toString().replace(/\/$/, '');
}

function readEffectiveSupabaseConfig() {
  const summary = getEnvSummary();
  const dev = parseEnvFile(DEV_ENV_PATH);
  const local = parseEnvFile(ENV_LOCAL_PATH);

  return {
    profile: summary.profile,
    supabaseUrl: summary.supabaseUrl,
    supabaseAnonKey: summary.supabaseAnonKey,
    platformAi:
      dev.get('VITE_PLATFORM_AI_ENABLED') ??
      local.get('VITE_PLATFORM_AI_ENABLED') ??
      'false',
    emailDelivery:
      dev.get('VITE_AUTH_EMAIL_DELIVERY_ENABLED') ??
      local.get('VITE_AUTH_EMAIL_DELIVERY_ENABLED') ??
      'false',
  };
}

export function writeMobileEnv({
  profile,
  platform,
  supabaseUrl = '',
  supabaseAnonKey = '',
  platformAi = 'false',
  emailDelivery = 'false',
} = {}) {
  const preserved = new Map();
  if (existsSync(MOBILE_ENV_PATH)) {
    for (const [key, value] of parseEnvFile(MOBILE_ENV_PATH)) {
      if (!MANAGED_MOBILE_KEYS.has(key)) preserved.set(key, value);
    }
  } else if (existsSync(MOBILE_ENV_EXAMPLE_PATH)) {
    for (const [key, value] of parseEnvFile(MOBILE_ENV_EXAMPLE_PATH)) {
      if (!MANAGED_MOBILE_KEYS.has(key)) preserved.set(key, value);
    }
  }

  const entries = new Map(preserved);
  const mobileUrl = resolveMobileSupabaseUrl(supabaseUrl, platform);

  if (profile === DEV_PROFILES.GUEST || !supabaseUrl || !supabaseAnonKey) {
    entries.set('EXPO_PUBLIC_SUPABASE_URL', '');
    entries.set('EXPO_PUBLIC_SUPABASE_ANON_KEY', '');
  } else {
    entries.set('EXPO_PUBLIC_SUPABASE_URL', mobileUrl);
    entries.set('EXPO_PUBLIC_SUPABASE_ANON_KEY', supabaseAnonKey);
  }

  entries.set('EXPO_PUBLIC_PLATFORM_AI_ENABLED', platformAi || 'false');
  entries.set('EXPO_PUBLIC_AUTH_EMAIL_DELIVERY_ENABLED', emailDelivery || 'false');

  const header = [
    '# Generated by npm run mobile:dev',
    `# Profile: ${profile ?? 'custom'}`,
    `# Platform: ${platform ?? 'ios'}`,
    '# Do not commit secrets.',
  ];

  writeFileSync(MOBILE_ENV_PATH, formatEnvFile(entries, header), 'utf8');

  return {
    path: MOBILE_ENV_PATH,
    supabaseUrl: entries.get('EXPO_PUBLIC_SUPABASE_URL') ?? '',
    platformAi: entries.get('EXPO_PUBLIC_PLATFORM_AI_ENABLED') ?? 'false',
  };
}

export function syncMobileEnvForProfile(profile, platform = MOBILE_PLATFORMS.IOS) {
  const config = readEffectiveSupabaseConfig();

  if (profile === DEV_PROFILES.GUEST) {
    return writeMobileEnv({ profile, platform });
  }

  if (profile === DEV_PROFILES.REMOTE || profile === DEV_PROFILES.LOCAL_SUPABASE) {
    return writeMobileEnv({
      profile,
      platform,
      supabaseUrl: config.supabaseUrl,
      supabaseAnonKey: config.supabaseAnonKey,
      platformAi: config.platformAi,
      emailDelivery: config.emailDelivery,
    });
  }

  return writeMobileEnv({
    profile: profile ?? 'custom',
    platform,
    supabaseUrl: config.supabaseUrl,
    supabaseAnonKey: config.supabaseAnonKey,
    platformAi: config.platformAi,
    emailDelivery: config.emailDelivery,
  });
}

export function getMobileEnvSummary() {
  const mobile = parseEnvFile(MOBILE_ENV_PATH);
  const effective = readEffectiveSupabaseConfig();
  return {
    hasMobileEnv: existsSync(MOBILE_ENV_PATH),
    mobileSupabaseUrl: mobile.get('EXPO_PUBLIC_SUPABASE_URL') ?? '',
    mobilePlatformAi: mobile.get('EXPO_PUBLIC_PLATFORM_AI_ENABLED') ?? '',
    effectiveProfile: effective.profile,
    effectiveSupabaseUrl: effective.supabaseUrl,
  };
}
